name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Dependencies
      uses: daaku/gh-action-apt-install@v4
      with:
        packages: libevent-dev
    - uses: actions/checkout@v3
    - run: pwd
    - run: ls -la .
    - run: ./autogen.sh
    - name: configure
      run: ./configure
    - name: make
      run: make
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: buildResult
        path: ./
